### ISSUE TITLE
Update licensing to include CC BY-SA for contents

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/openness-framework#37]
> :pray: thx @vlamy for raising this issue

"Open Content" projects lack a clear indication of a by default license for non-code contents.

## Context

We already [defined this](https://github.com/blindnet-io/blindnet.dev#license) in blindnet.dev, with a dual MIT / CC BY-SA license.

This issue is here to enforce this decision for all blindnet contents.

## Sub-tasks

- [ ] update / extend [DR 0001 - Choose by default license(s) for Open Source projects](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0001-oss-license.md) to add CC BY-SA
- [ ] clearly indicate when and why to specify a specific license for a specific content
- [ ] clearly indicate this by default dual licensing in all Open Content repositories
    - [ ] https://github.com/blindnet-io/openness-framework
    - [ ] https://github.com/blindnet-io/devrel-management
    - [ ] https://github.com/blindnet-io/product-management
